# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82560b735cb282cf14973a296fb0532da6e384fe4de32a1aa868efc15c4fd80799020eff76770774039a08f7ffb2d12e466d8ec518e2fce6cd93096e0d9072f8

test:
  secret_key_base: 276b8c9e131da9728dceb0b74381ae791e71ff83fcef1074627cd0b819d991293e02415064fa20219050464b61df1bf35fcf0dc7c87091ff8091faadd97f33ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
